// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeIsc_ZhDokDk_2IwWXL7cYkKqbfkOXB8',
    appId: '1:1005197857738:web:d103cee51ce07410983533',
    messagingSenderId: '1005197857738',
    projectId: 'mlkit-email-detector',
    authDomain: 'mlkit-email-detector.firebaseapp.com',
    storageBucket: 'mlkit-email-detector.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8IvY0XeoWl0JuV9UvYwkVp0mcZKrmY0',
    appId: '1:1005197857738:android:9104d33ad53dbe80983533',
    messagingSenderId: '1005197857738',
    projectId: 'mlkit-email-detector',
    storageBucket: 'mlkit-email-detector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpV22KZ2V13LGC-IMBz_RTZ-WiPD5Nd4g',
    appId: '1:1005197857738:ios:5afcefc897eaaecf983533',
    messagingSenderId: '1005197857738',
    projectId: 'mlkit-email-detector',
    storageBucket: 'mlkit-email-detector.appspot.com',
    iosBundleId: 'com.example.mlkitEmailDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpV22KZ2V13LGC-IMBz_RTZ-WiPD5Nd4g',
    appId: '1:1005197857738:ios:5afcefc897eaaecf983533',
    messagingSenderId: '1005197857738',
    projectId: 'mlkit-email-detector',
    storageBucket: 'mlkit-email-detector.appspot.com',
    iosBundleId: 'com.example.mlkitEmailDetector',
  );
}
